// Code generated by go2go; DO NOT EDIT.


//line export_test.go2:5
package sort2

//line export_test.go2:5
import (
//line export_test.go2:5
 "fmt"
//line export_test.go2:5
 "math"
//line export_test.go2:5
 "math/rand"
//line export_test.go2:5
 "runtime"
//line export_test.go2:5
 "strconv"
//line export_test.go2:5
 "testing"
//line export_test.go2:5
)

//line export_test.go2:5
type Importable୦ int

//line export_test.go2:5
var _ = fmt.Errorf
//line export_test.go2:5
var _ = math.Abs
//line export_test.go2:5
var _ = rand.ExpFloat64
//line export_test.go2:5
var _ = runtime.BlockProfile
//line export_test.go2:5
var _ = strconv.AppendBool
//line export_test.go2:5
var _ = testing.AllocsPerRun
